micronaut:
  application:
    name: greenlac
  server:
    port: 8080

netty:
  default:
    allocator:
      max-order: 3

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  metrics:
    enabled: true
    sensitive: false

greenlac:
  endpoint-lambda-edge: http://localhost:4711
  endpoint-lambda-core: https://gydrsqutj5.execute-api.us-east-1.amazonaws.com/default/230mb_model_1_image
  buffer-size: 100
  load-balancer-policy: core
  cpu-utilization-threshold: 50
  memory-utilization-threshold: 50
