spring:
  application:
    name: greenlac
server:
  port: 8080

greenlac:
  endpoint:
    core: https://gydrsqutj5.execute-api.us-east-1.amazonaws.com/default/230mb_model_1_image
    edges:
      localEdge: http://localhost:4711
      remoteEdges:
        - http://ec2-35-183-144-137.ca-central-1.compute.amazonaws.com:8080/greenlac/v1/ml

  scaling:
    policy: edge # core-edge-pc, core-edge-pe, edge, core
    utilizationThreshold:
      cpu: 10
      memory: 50

  loadBalancer:
    buffersize: 100
